apiVersion: v1
kind: Service
metadata:
  name: {{ include "onos.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "onos.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.globalService }}
    {{- include "globalServiceAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.onos.service.type }}
  ports:
    - name: onoswww
      port: {{ .Values.onos.service.ports.onoswww.port }}
      targetPort: {{ .Values.onos.service.ports.onoswww.targetPort }}
      protocol: {{ .Values.onos.service.ports.onoswww.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.onoswww.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.onoswww.nodePort }}
      {{- end }}
    - name: onoscli
      port: {{ .Values.onos.service.ports.onoscli.port }}
      targetPort: {{ .Values.onos.service.ports.onoscli.targetPort }}
      protocol: {{ .Values.onos.service.ports.onoscli.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.onoscli.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.onoscli.nodePort }}
      {{- end }}
    - name: intracltcp
      port: {{ .Values.onos.service.ports.intracltcp.port }}
      targetPort: {{ .Values.onos.service.ports.intracltcp.targetPort }}
      protocol: {{ .Values.onos.service.ports.intracltcp.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.intracltcp.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.intracltcp.nodePort }}
      {{- end }}
    - name: intracludp
      port: {{ .Values.onos.service.ports.intracludp.port }}
      targetPort: {{ .Values.onos.service.ports.intracludp.targetPort }}
      protocol: {{ .Values.onos.service.ports.intracludp.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.intracludp.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.intracludp.nodePort }}
      {{- end }}
    - name: sflow
      port: {{ .Values.onos.service.ports.sflow.port }}
      targetPort: {{ .Values.onos.service.ports.sflow.targetPort }}
      protocol: {{ .Values.onos.service.ports.sflow.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.sflow.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.sflow.nodePort }}
      {{- end }}
    - name: ssh
      port: {{ .Values.onos.service.ports.ssh.port }}
      targetPort: {{ .Values.onos.service.ports.ssh.targetPort }}
      protocol: {{ .Values.onos.service.ports.ssh.protocol }}
      {{- if and (or (eq .Values.onos.service.type "NodePort") (eq .Values.onos.service.type "LoadBalancer")) (not (empty .Values.onos.service.ports.ssh.nodePort)) }}
      nodePort: {{ .Values.onos.service.ports.ssh.nodePort }}
      {{- end }}
  selector:
    {{- include "onos.selectorLabels" . | nindent 4 }}
